apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mendix-NAME-stateful
  labels:
    app: mendix-NAME
spec:
  serviceName: mendix-NAME
  replicas: 1 
  selector:
    matchLabels:
      app: mendix-NAME
  template:
    metadata:
      labels:
        app: mendix-NAME
    spec:
      containers:
        - name: mendix-NAME
          image: IMAGE 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/build/data/files"
              name: mendix-data
          env:
            - name: ADMIN_PASSWORD
              value: "MxAdmin" 
            - name: DATABASE_ENDPOINT
              value: postgres://postgres:4fjPLHgUDI@169.45.189.35:30131/NAME
            - name: DEVELOPMENT_MODE
              value: "true"
      volumes:
        - hostPath:
            path: "/tmp"
          name: mendix-data
